[[language]]
name = "rust"

[language-server.rust-analyzer.config.check]
command = "clippy"
inlayHints = { typeHints = { enable = true } }

[[grammar]]
name = "rust"
source = { git = "https://github.com/tree-sitter/tree-sitter-rust", rev = "0431a2c60828731f27491ee9fdefe25e250ce9c9" }

[[languages]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

[language-server.gopls.config]
gofumpt = true
staticcheck = true
semanticTokens = true

[language-server.gopls.config.codelenses]
gc_details = true
generate = true

[language-server.gopls.config.analyses]
fieldalignment = true

[language-server.gopls.config.hints]
compositeLiteralFields = true
constantValues = true
parameterNames = true
rangeVariableTypes = true

[[language]]
name = "racket"
auto-format = true

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

[language-server.yaml-language-server.config.yaml.schemas]
kubernetes = "*.yaml"
"https://gitlab.com/gitlab-org/gitlab/-/raw/master/app/assets/javascripts/editor/schema/ci.json" = ".gitlab-ci.{yml,yaml})"
"https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json" = "*compose*.{yml,yaml}"
"https://json.schemastore.org/github-workflow.json" = ".github/workflows/*.{yml,yaml}"
"https://raw.githubusercontent.com/ansible-community/schemas/main/f/ansible-tasks.json" = "roles/{tasks,handlers}/*.{yml,yaml}"

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

[[language]]
name = "python"
language-servers = [ "pyright",  "ruff" ]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "strict"

[language-server.ruff]
command = "ruff-lsp"

[language.formatter]
command = "black"
args = ["--line-length", "100",  "-"]

[[language-server.typescript-language-server.config]]
includeInlayParameterNameHints = "all"

[[language]]
name = "ocaml"
formatter = { command = "ocamlformat", args = [
  "-",
  "--impl",
  "--enable-outside-detected-project", # Enable only if you want to format files outside of projects
] }
